// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.999
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebAccessibilityChecker
{
    static class Vsix
    {
        public const string Id = "F3A70276-0754-428D-A26E-3A782BD9DACC";
        public const string Name = "Web Accessibility Checker 2022";
        public const string Description = @"Perform accessibility checks on any ASP.NET web application. Fully customizable and supports all the major international accessibility standards using axe-core.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "web, accessibility, a11y, wcag, section 508, wai, asp.net, axe";
    }
}
